ark:
  container_name: ark
  image: bigdaddymccarron/ark
  environment:
    - BRANCH=master
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - SERVERPASSWORD="" 
    - ADMINPASSWORD=adminpassword
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=EST
    - GID=281
    - UID=1007
  volumes:
    - /mnt/user/Dockers/Ark/server:/ark
    - /mnt/cache/Dockers/Ark/Steam:/root/Steam 
  ports:
    - 7777:7777/udp
    - 7777:7777
    - 27015:27015/udp
    - 27015:27015
    - 32330:32330
